### ISSUE TITLE
TypeError with -i and SPAdes

### ISSUE THREAD

**Issue by MarieLataretu** [almiheenko/AGB#2]
Hi,
I tried the nice ``-i`` option with a SPAdes assembly, but I get a ``TypeError: must be str, not NoneType``. 

The command 
```
agb.py -i assembly/spades/ -a spades
```
gives
```
File "~/miniconda3/envs/agb/bin/agb.py", line 153, in <module>
    main()
  File "~/miniconda3/envs/agb/bin/agb.py", line 129, in main
    opts.output_dir, opts.input_fasta, opts.min_edge_len)
  File "~/miniconda3/envs/agb/bin/agb.py", line 70, in parse_assembler_output
    dict_edges, contig_edges, edges_fpath = parse_spades_output(input_dirpath, output_dirpath, min_edge_len)
  File "~/miniconda3/envs/agb/lib/python3.6/site-packages/agb_src/scripts/info_parser.py", line 41, in parse_spades_output
    dict_edges = parse_gfa(gfa_fpath, min_edge_len, input_dirpath, assembler="spades")
  File "~/miniconda3/envs/agb/lib/python3.6/site-packages/agb_src/scripts/graph_parser.py", line 212, in parse_gfa
    print("Parsing " + gfa_fpath + "...")
TypeError: must be str, not NoneType
```

With SPAdes version 3.13.0 and 3.13.1 I get ``assembly_graph_with_scaffolds.gfa`` not ``assembly_graph.gfa``. 

So ``parse_spades_output`` in ``info_parser.py`` should also look for ``assembly_graph_with_scaffolds.gfa``.

Best
Marie

**Comment by almiheenko** [comment]
Hi Marie,

Thank you for reporting this issue! I've updated AGB with regards to a new version of SPAdes. Please let me know if you have any issues.

Best regards,
Alla

**Comment by MarieLataretu** [comment]
Hi Alla,
thanks, it works now !

**Comment by MarieLataretu** [comment]
Hi Alla,

I have an other question regarding the usage with SOAPdenovo2: which 
file is expected as input? I tried all of my SOAPdenovo2 output files 
(.Arc, .links, .scaf_gap, .contig, .scafSeq, .bubbleInScaff, 
.newContigIndex, .scafStatistics, .ContigIndex, .peGrads, .updated.edge, 
.contigPosInscaff, .preArc, .vertex, .gapSeq, .preGraphBasic, .kmerFreq, 
.scaf), but I get either

Traceback (most recent call last):
   File "~/miniconda3/envs/agb/bin/agb.py", line 154, in <module>
     main()
   File "~/miniconda3/envs/agb/bin/agb.py", line 130, in main
     opts.output_dir, opts.input_fasta, opts.min_edge_len)
   File "~/miniconda3/envs/agb/bin/agb.py", line 79, in 
parse_assembler_output
     for edge_id, edge in dict_edges.items():
UnboundLocalError: local variable 'dict_edges' referenced before assignment

or

Output folder of soapdenovo2 assembler can not be parsed! Supported 
assemblers: Canu, Flye, SPAdes. More assemblers will be added in the 
next release.
To visualize the assembly graph produced by this assembler, you should 
manually specify the assembly graph file in GFA/FASTG/GraphViz formats 
using --graph option and (optionally) file with edge sequences using 
--fasta option

I'm not sure if there is some SOAPdenovo2 option that I'm missing to get 
a fastg file...

The command is
agb.py --graph soapdenovo2k17.contig -a soapdenovo2 [--fasta 
soapdenovo2k17.contig]
(--fasta gives no change)


Best,
Marie



On 7/23/19 11:05 AM, almiheenko wrote:
> Hi Marie,
> 
> Thank you for reporting this issue! I've updated AGB with regards to a new version of SPAdes. Please let me know if you have any issues.
> 
> Best regards,
> Alla
> 

-- 
Marie Lataretu, M. Sc., PhD student
RNA Bioinformatics and High Throughput Analysis Jena
Friedrich Schiller University Jena
Faculty of Mathematics and Computer Science
Jena, Germany

**Comment by almiheenko** [comment]
Hi Marie,

AGB accepts files in GFA, FASTG or GraphViz formats. Unfortunately, SOAPdenovo2 does not produce such outputs. However, gfatools (https://github.com/lh3/gfatools) can convert SOAPdenovo output to GFA file. It is included in AGB package and can be used like this: `~/miniconda3/envs/agb/lib/python3.6/site-packages/agb_src/external_tools/k8-darwin|linux `(depending on your OS) ` ~/miniconda3/envs/agb/lib/python3.6/site-packages/agb_src/external_tools/gfatools soap2gfa <SOAPdenovo2prefix>`(soapdenovo2k17 in your case)` > soap.gfa`. And then you can run AGB using --graph soap.gfa.

Best regards,
Alla

**Comment by MarieLataretu** [comment]
Hi Alla,

thanks for your answer!

With the external tools I was able to create the gfa file! (And it works 
with AGB :)).
But I had to download it manually from GitHub, because it somehow does 
not come with the conda installation. Maybe you missed to include that 
directory (AGB/agb_src/external_tools/)?

Best,
Marie

On 7/25/19 6:14 PM, almiheenko wrote:
> Hi Marie,
> 
> AGB accepts files in GFA, FASTG or GraphViz formats. Unfortunately, SOAPdenovo2 does not produce such outputs. However, gfatools (https://github.com/lh3/gfatools) can convert SOAPdenovo output to GFA file. It is included in AGB package and can be used like this: `~/miniconda3/envs/agb/lib/python3.6/site-packages/agb_src/external_tools/k8-darwin|linux `(depending on your OS) ` ~/miniconda3/envs/agb/lib/python3.6/site-packages/agb_src/external_tools/gfatools soap2gfa <SOAPdenovo2prefix>`(soapdenovo2k17 in your case)` > soap.gfa`. And then you can run AGB using --graph soap.gfa.
> 
> Best regards,
> Alla
> 

-- 
Marie Lataretu, M. Sc., PhD student
RNA Bioinformatics and High Throughput Analysis Jena
Friedrich Schiller University Jena
Faculty of Mathematics and Computer Science
Jena, Germany
