### ISSUE TITLE
AttributeError: module 'networkx' has no attribute 'weakly_connected_component_subgraphs'

### ISSUE THREAD

**Issue by Malabady** [almiheenko/AGB#4]
Hi,

I ran the following command:
 $ agb.py -i rosea8-trim-assemble -a Canu

And got the following error:

Extracting edge sequences from rosea8-trim-assemble/Spu.unitigs.gfa...
Parsing agb_output/Spu.unitigs.gfa...
Finish parsing.
No information about contig mappings to the reference genome
No information about edge mappings to the reference genome
Building JSON files...
Traceback (most recent call last):
  File "/home/malabady/.conda/envs/AGB/bin/agb.py", line 154, in <module>
    main()
  File "/home/malabady/.conda/envs/AGB/bin/agb.py", line 144, in main
    build_jsons(dict_edges, opts.input_dir, json_output_dirpath, mapping_info, chrom_names, edge_by_chrom, contig_edges, opts.assembler)
  File "/home/malabady/.conda/envs/AGB/lib/python3.6/site-packages/agb_src/scripts/viewer_builder.py", line 37, in build_jsons
    edges_by_component = process_graph(g, undirected_g, dict_edges, edges_by_nodes, two_way_edges, output_dirpath, 'def', assembler)
  File "/home/malabady/.conda/envs/AGB/lib/python3.6/site-packages/agb_src/scripts/graph_analysis.py", line 89, in process_graph
    connected_components = list(nx.weakly_connected_component_subgraphs(g))
AttributeError: module 'networkx' has no attribute 'weakly_connected_component_subgraphs'

Do you know what's wrong? 

Thanks,

**Comment by berombau** [comment]
networkx 2.4 removed `weakly_connected_component_subgraphs`
 [link](https://networkx.github.io/documentation/stable/release/release_2.4.html)

You can add this restriction in conda with `conda install networkx=2.3`

**Comment by almiheenko** [comment]
Thank you for reporting the issue! I've added requirements for networkx version in conda package.

**Comment by truongvanthong** [comment]
Good
